workflows:
  ios-workflow:
    name: iOS Build for App Store
    max_build_duration: 60

    integrations:
      app_store_connect: |
        key_id: R97NT58B23
        issuer_id: 2f594fd1-0323-44bb-8457-7e1575694497
        auth: integration

    environment:
      flutter: stable
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.simfour.auditor

    scripts:
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get

      - name: Install signing files
        script: |
          keychain initialize
          app-store-connect fetch-signing-files com.simfour.auditor --type IOS_APP_STORE
          keychain add-certificates
          xcode-project use-profiles

      - name: Build IPA for App Store
        script: |
          flutter build ipa --release --export-method app-store

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true